import { COLORS } from "@/lib/colors.ts";

export const NER_MODELS_NAMES = [
  'bertBaseNer',
  'camembertNerPii',
  'distilbertBaseMultiCasedNer',
  'nermembertLarge4Entities',
  'nermembert24Entities',
  'nermemberta4Entities',
] as const;

export type NERModel = typeof NER_MODELS_NAMES[number];

export const CUSTOM_PAGE_SPLIT_TOKEN = "\n\n[CUSTOM_PAGE_TOKEN]\n\n";

type EntityMeta = {
  title: string;
  label: string;
  dot: string;
  badge: string;
  highlight: string;
};

type NERModelMeta = {
  [key in NERModel]: {
    label: string;
    url: string;
    size: string;
    entities: {
      [key: string]: EntityMeta;
    };
  };
};

export const NER_MODELS: NERModelMeta = {
  bertBaseNer: {
    label: 'BERT Base NER',
    url: 'https://huggingface.co/dslim/bert-base-NER',
    size: '430 MB',
    entities: {
      DATE: {
        label: "Date",
        title: "Dates",
        dot: COLORS.dot.fuchsia,
        badge: COLORS.badge.fuchsia,
        highlight: COLORS.highlight.fuchsia,
      },
      EMAIL: {
        label: "Email",
        title: "Emails",
        dot: COLORS.dot.amber,
        badge: COLORS.badge.amber,
        highlight: COLORS.highlight.amber,
      },
      ID: {
        label: "ID",
        title: "ID",
        dot: COLORS.dot.red,
        badge: COLORS.badge.red,
        highlight: COLORS.highlight.red,
      },
      IP: {
        label: "Adresse IP",
        title: "Adresses IP",
        dot: COLORS.dot.red,
        badge: COLORS.badge.red,
        highlight: COLORS.highlight.red,
      },
      LOC: {
        label: "Lieu",
        title: "Lieux",
        dot: COLORS.dot.green,
        badge: COLORS.badge.green,
        highlight: COLORS.highlight.green,
      },
      MANUAL: {
        label: "Ajout manuel",
        title: "Ajouts manuels",
        dot: COLORS.dot.fuchsia,
        badge: COLORS.badge.fuchsia,
        highlight: COLORS.highlight.fuchsia,
      },
      MISC: {
        label: "Autre",
        title: "Autres",
        dot: COLORS.dot.purple,
        badge: COLORS.badge.purple,
        highlight: COLORS.highlight.purple,
      },
      ORG: {
        label: "Organisation",
        title: "Organisations",
        dot: COLORS.dot.teal,
        badge: COLORS.badge.teal,
        highlight: COLORS.highlight.teal,
      },
      PER: {
        label: "Personne",
        title: "Personnes",
        dot: COLORS.dot.blue,
        badge: COLORS.badge.blue,
        highlight: COLORS.highlight.blue,
      },
      URL: {
        label: "URL",
        title: "Links",
        dot: COLORS.dot.red,
        badge: COLORS.badge.red,
        highlight: COLORS.highlight.red,
      },
    },
  },
  camembertNerPii: {
    label: 'CamemBERT NER PII',
    url: 'https://huggingface.co/Anonym-IA/V2-camembert-ner-pii-onnx-fp32',
    size: '440 MB',
    entities: {
      ACCOUNTNUMBER: {
        label: "N° de compte",
        title: "Numéros de compte",
        dot: COLORS.dot.teal,
        badge: COLORS.badge.teal,
        highlight: COLORS.highlight.teal,
      },
      AGE: {
        label: "Âge",
        title: "Âges",
        dot: COLORS.dot.blue,
        badge: COLORS.badge.blue,
        highlight: COLORS.highlight.blue,
      },
      AMOUNT: {
        label: "Montant",
        title: "Montants",
        dot: COLORS.dot.teal,
        badge: COLORS.badge.teal,
        highlight: COLORS.highlight.teal,
      },
      BITCOINADDRESS: {
        label: "Adresse BTC",
        title: "Adresses Bitcoin",
        dot: COLORS.dot.amber,
        badge: COLORS.badge.amber,
        highlight: COLORS.highlight.amber,
      },
      CODE_POSTAL: {
        label: "Code postal",
        title: "Codes postaux",
        dot: COLORS.dot.purple,
        badge: COLORS.badge.purple,
        highlight: COLORS.highlight.purple,
      },
      COUNTRY: {
        label: "Pays",
        title: "Pays",
        dot: COLORS.dot.purple,
        badge: COLORS.badge.purple,
        highlight: COLORS.highlight.purple,
      },
      CREDITCARD: {
        label: "N° de CB",
        title: "Numéros de CB",
        dot: COLORS.dot.teal,
        badge: COLORS.badge.teal,
        highlight: COLORS.highlight.teal,
      },
      CURRENCY: {
        label: "Devise",
        title: "Devises",
        dot: COLORS.dot.amber,
        badge: COLORS.badge.amber,
        highlight: COLORS.highlight.amber,
      },
      DATE: {
        label: "Date",
        title: "Dates",
        dot: COLORS.dot.amber,
        badge: COLORS.badge.amber,
        highlight: COLORS.highlight.amber,
      },
      DOB: {
        label: "Date de naissance",
        title: "Dates de naissance",
        dot: COLORS.dot.amber,
        badge: COLORS.badge.amber,
        highlight: COLORS.highlight.amber,
      },
      EMAIL: {
        label: "Email",
        title: "Emails",
        dot: COLORS.dot.amber,
        badge: COLORS.badge.amber,
        highlight: COLORS.highlight.amber,
      },
      ETHEREUMADDRESS: {
        label: "Adresse ETH",
        title: "Adresses Ethereum",
        dot: COLORS.dot.amber,
        badge: COLORS.badge.amber,
        highlight: COLORS.highlight.amber,
      },
      EYECOLOR: {
        label: "Couleur d'yeux",
        title: "Couleurs d'yeux",
        dot: COLORS.dot.blue,
        badge: COLORS.badge.blue,
        highlight: COLORS.highlight.blue,
      },
      GENDER: {
        label: "Genre",
        title: "Genres",
        dot: COLORS.dot.blue,
        badge: COLORS.badge.blue,
        highlight: COLORS.highlight.blue,
      },
      HEIGHT: {
        label: "Hauteur",
        title: "Hauteurs",
        dot: COLORS.dot.blue,
        badge: COLORS.badge.blue,
        highlight: COLORS.highlight.blue,
      },
      ID: {
        label: "ID",
        title: "ID",
        dot: COLORS.dot.teal,
        badge: COLORS.badge.teal,
        highlight: COLORS.highlight.teal,
      },
      IP: {
        label: "Adresse IP",
        title: "Adresses IP",
        dot: COLORS.dot.teal,
        badge: COLORS.badge.teal,
        highlight: COLORS.highlight.teal,
      },
      JOBAREA: {
        label: "Lieu de travail",
        title: "Lieux de travail",
        dot: COLORS.dot.green,
        badge: COLORS.badge.green,
        highlight: COLORS.highlight.green,
      },
      JOBTITLE: {
        label: "Profession",
        title: "Professions",
        dot: COLORS.dot.green,
        badge: COLORS.badge.green,
        highlight: COLORS.highlight.green,
      },
      JOBTYPE: {
        label: "Profession",
        title: "Types de profession",
        dot: COLORS.dot.green,
        badge: COLORS.badge.green,
        highlight: COLORS.highlight.green,
      },
      MAC: {
        label: "Adresse MAC",
        title: "Adresses MAC",
        dot: COLORS.dot.teal,
        badge: COLORS.badge.teal,
        highlight: COLORS.highlight.teal,
      },
      MANUAL: {
        label: "Ajout manuel",
        title: "Ajouts manuels",
        dot: COLORS.dot.fuchsia,
        badge: COLORS.badge.fuchsia,
        highlight: COLORS.highlight.fuchsia,
      },
      NOM_PERSONNE: {
        label: "Nom de famille",
        title: "Noms de famille",
        dot: COLORS.dot.blue,
        badge: COLORS.badge.blue,
        highlight: COLORS.highlight.blue,
      },
      NOM_SOCIETE: {
        label: "Entreprise",
        title: "Organisations",
        dot: COLORS.dot.green,
        badge: COLORS.badge.green,
        highlight: COLORS.highlight.green,
      },
      NOM_VOIE: {
        label: "Voie",
        title: "Noms de rues",
        dot: COLORS.dot.purple,
        badge: COLORS.badge.purple,
        highlight: COLORS.highlight.purple,
      },
      NUM_DOSSIER: {
        label: "N° de dossier",
        title: "Numéros de dossier",
        dot: COLORS.dot.teal,
        badge: COLORS.badge.teal,
        highlight: COLORS.highlight.teal,
      },
      NUM_SECURITE_SOCIALE: {
        label: "Sécurité sociale",
        title: "Sécurité sociale",
        dot: COLORS.dot.teal,
        badge: COLORS.badge.teal,
        highlight: COLORS.highlight.teal,
      },
      NUMERO_VOIE: {
        label: "Num voie",
        title: "Numéros de voie",
        dot: COLORS.dot.purple,
        badge: COLORS.badge.purple,
        highlight: COLORS.highlight.purple,
      },
      PASSWORD: {
        label: "Mot de passe",
        title: "Mots de passe",
        dot: COLORS.dot.blue,
        badge: COLORS.badge.blue,
        highlight: COLORS.highlight.blue,
      },
      PRENOM_PERSONNE: {
        label: "Prénom",
        title: "Prénoms",
        dot: COLORS.dot.blue,
        badge: COLORS.badge.blue,
        highlight: COLORS.highlight.blue,
      },
      REF_CADASTRALE: {
        label: "Référence cadastrale",
        title: "Références cadastrales",
        dot: COLORS.dot.teal,
        badge: COLORS.badge.teal,
        highlight: COLORS.highlight.teal,
      },
      SECONDARYADDRESS: {
        label: "Adresse secondaire",
        title: "Adresses secondaires",
        dot: COLORS.dot.amber,
        badge: COLORS.badge.amber,
        highlight: COLORS.highlight.amber,
      },
      STATE: {
        label: "Région",
        title: "Régions",
        dot: COLORS.dot.purple,
        badge: COLORS.badge.purple,
        highlight: COLORS.highlight.purple,
      },
      TELEPHONE: {
        label: "Téléphone",
        title: "Téléphones",
        dot: COLORS.dot.blue,
        badge: COLORS.badge.blue,
        highlight: COLORS.highlight.blue,
      },
      TIME: {
        label: "Temps",
        title: "Temps",
        dot: COLORS.dot.amber,
        badge: COLORS.badge.amber,
        highlight: COLORS.highlight.amber,
      },
      URL: {
        label: "URL",
        title: "URLs",
        dot: COLORS.dot.amber,
        badge: COLORS.badge.amber,
        highlight: COLORS.highlight.amber,
      },
      USERAGENT: {
        label: "Useragent",
        title: "Useragents",
        dot: COLORS.dot.amber,
        badge: COLORS.badge.amber,
        highlight: COLORS.highlight.amber,
      },
      USERNAME: {
        label: "Nom d'utilisateur",
        title: "Noms d'utilisateurs",
        dot: COLORS.dot.blue,
        badge: COLORS.badge.blue,
        highlight: COLORS.highlight.blue,
      },
      VEHICLEVIN: {
        label: "N° de série (véhicule)",
        title: "Numéros de série (véhicule)",
        dot: COLORS.dot.teal,
        badge: COLORS.badge.teal,
        highlight: COLORS.highlight.teal,
      },
      VEHICLEVRM: {
        label: "N° Immatriculation",
        title: "Immatriculations (véhicule)",
        dot: COLORS.dot.teal,
        badge: COLORS.badge.teal,
        highlight: COLORS.highlight.teal,
      },
      VILLE: {
        label: "Ville",
        title: "Villes",
        dot: COLORS.dot.purple,
        badge: COLORS.badge.purple,
        highlight: COLORS.highlight.purple,
      },
    },
  },
  nermembert24Entities: {
    label: 'NERmembert2 4 entities',
    url: 'https://huggingface.co/CATIE-AQ/NERmembert2-4entities',
    size: '440 MB',
    entities: {
      DATE: {
        label: "Date",
        title: "Dates",
        dot: COLORS.dot.fuchsia,
        badge: COLORS.badge.fuchsia,
        highlight: COLORS.highlight.fuchsia,
      },
      EMAIL: {
        label: "Email",
        title: "Emails",
        dot: COLORS.dot.amber,
        badge: COLORS.badge.amber,
        highlight: COLORS.highlight.amber,
      },
      ID: {
        label: "ID",
        title: "ID",
        dot: COLORS.dot.red,
        badge: COLORS.badge.red,
        highlight: COLORS.highlight.red,
      },
      IP: {
        label: "Adresse IP",
        title: "Adresses IP",
        dot: COLORS.dot.red,
        badge: COLORS.badge.red,
        highlight: COLORS.highlight.red,
      },
      LOC: {
        label: "Lieu",
        title: "Lieux",
        dot: COLORS.dot.green,
        badge: COLORS.badge.green,
        highlight: COLORS.highlight.green,
      },
      MANUAL: {
        label: "Ajout manuel",
        title: "Ajouts manuels",
        dot: COLORS.dot.fuchsia,
        badge: COLORS.badge.fuchsia,
        highlight: COLORS.highlight.fuchsia,
      },
      MISC: {
        label: "Autre",
        title: "Autres",
        dot: COLORS.dot.purple,
        badge: COLORS.badge.purple,
        highlight: COLORS.highlight.purple,
      },
      ORG: {
        label: "Organisation",
        title: "Organisations",
        dot: COLORS.dot.teal,
        badge: COLORS.badge.teal,
        highlight: COLORS.highlight.teal,
      },
      PER: {
        label: "Personne",
        title: "Personnes",
        dot: COLORS.dot.blue,
        badge: COLORS.badge.blue,
        highlight: COLORS.highlight.blue,
      },
      URL: {
        label: "URL",
        title: "Links",
        dot: COLORS.dot.red,
        badge: COLORS.badge.red,
        highlight: COLORS.highlight.red,
      },
    },
  },
  nermembertLarge4Entities: {
    label: 'NERmembert Large 4 entities',
    url: 'https://huggingface.co/CATIE-AQ/NERmembert-large-4entities',
    size: '1.4 GB',
    entities: {
      DATE: {
        label: "Date",
        title: "Dates",
        dot: COLORS.dot.fuchsia,
        badge: COLORS.badge.fuchsia,
        highlight: COLORS.highlight.fuchsia,
      },
      EMAIL: {
        label: "Email",
        title: "Emails",
        dot: COLORS.dot.amber,
        badge: COLORS.badge.amber,
        highlight: COLORS.highlight.amber,
      },
      ID: {
        label: "ID",
        title: "ID",
        dot: COLORS.dot.red,
        badge: COLORS.badge.red,
        highlight: COLORS.highlight.red,
      },
      IP: {
        label: "Adresse IP",
        title: "Adresses IP",
        dot: COLORS.dot.red,
        badge: COLORS.badge.red,
        highlight: COLORS.highlight.red,
      },
      LOC: {
        label: "Lieu",
        title: "Lieux",
        dot: COLORS.dot.green,
        badge: COLORS.badge.green,
        highlight: COLORS.highlight.green,
      },
      MANUAL: {
        label: "Ajout manuel",
        title: "Ajouts manuels",
        dot: COLORS.dot.fuchsia,
        badge: COLORS.badge.fuchsia,
        highlight: COLORS.highlight.fuchsia,
      },
      MISC: {
        label: "Autre",
        title: "Autres",
        dot: COLORS.dot.purple,
        badge: COLORS.badge.purple,
        highlight: COLORS.highlight.purple,
      },
      ORG: {
        label: "Organisation",
        title: "Organisations",
        dot: COLORS.dot.teal,
        badge: COLORS.badge.teal,
        highlight: COLORS.highlight.teal,
      },
      PER: {
        label: "Personne",
        title: "Personnes",
        dot: COLORS.dot.blue,
        badge: COLORS.badge.blue,
        highlight: COLORS.highlight.blue,
      },
      URL: {
        label: "URL",
        title: "Links",
        dot: COLORS.dot.red,
        badge: COLORS.badge.red,
        highlight: COLORS.highlight.red,
      },
    },
  },
  nermemberta4Entities: {
    label: 'NERmemberta 4 entities',
    url: 'https://huggingface.co/CATIE-AQ/NERmemberta-4entities',
    size: '440 MB',
    entities: {
      DATE: {
        label: "Date",
        title: "Dates",
        dot: COLORS.dot.fuchsia,
        badge: COLORS.badge.fuchsia,
        highlight: COLORS.highlight.fuchsia,
      },
      EMAIL: {
        label: "Email",
        title: "Emails",
        dot: COLORS.dot.amber,
        badge: COLORS.badge.amber,
        highlight: COLORS.highlight.amber,
      },
      ID: {
        label: "ID",
        title: "ID",
        dot: COLORS.dot.red,
        badge: COLORS.badge.red,
        highlight: COLORS.highlight.red,
      },
      IP: {
        label: "Adresse IP",
        title: "Adresses IP",
        dot: COLORS.dot.red,
        badge: COLORS.badge.red,
        highlight: COLORS.highlight.red,
      },
      LOC: {
        label: "Lieu",
        title: "Lieux",
        dot: COLORS.dot.green,
        badge: COLORS.badge.green,
        highlight: COLORS.highlight.green,
      },
      MANUAL: {
        label: "Ajout manuel",
        title: "Ajouts manuels",
        dot: COLORS.dot.fuchsia,
        badge: COLORS.badge.fuchsia,
        highlight: COLORS.highlight.fuchsia,
      },
      MISC: {
        label: "Autre",
        title: "Autres",
        dot: COLORS.dot.purple,
        badge: COLORS.badge.purple,
        highlight: COLORS.highlight.purple,
      },
      ORG: {
        label: "Organisation",
        title: "Organisations",
        dot: COLORS.dot.teal,
        badge: COLORS.badge.teal,
        highlight: COLORS.highlight.teal,
      },
      PER: {
        label: "Personne",
        title: "Personnes",
        dot: COLORS.dot.blue,
        badge: COLORS.badge.blue,
        highlight: COLORS.highlight.blue,
      },
      URL: {
        label: "URL",
        title: "Links",
        dot: COLORS.dot.red,
        badge: COLORS.badge.red,
        highlight: COLORS.highlight.red,
      },
    },
  },
  distilbertBaseMultiCasedNer: {
    label: 'DistilBERT Base Muti NER',
    url: 'https://huggingface.co/Davlan/distilbert-base-multilingual-cased-ner-hrl',
    size: '250 MB',
    entities: {
      DATE: {
        label: "Date",
        title: "Dates",
        dot: COLORS.dot.fuchsia,
        badge: COLORS.badge.fuchsia,
        highlight: COLORS.highlight.fuchsia,
      },
      EMAIL: {
        label: "Email",
        title: "Emails",
        dot: COLORS.dot.amber,
        badge: COLORS.badge.amber,
        highlight: COLORS.highlight.amber,
      },
      ID: {
        label: "ID",
        title: "ID",
        dot: COLORS.dot.red,
        badge: COLORS.badge.red,
        highlight: COLORS.highlight.red,
      },
      IP: {
        label: "Adresse IP",
        title: "Adresses IP",
        dot: COLORS.dot.red,
        badge: COLORS.badge.red,
        highlight: COLORS.highlight.red,
      },
      LOC: {
        label: "Lieu",
        title: "Lieux",
        dot: COLORS.dot.green,
        badge: COLORS.badge.green,
        highlight: COLORS.highlight.green,
      },
      MANUAL: {
        label: "Ajout manuel",
        title: "Ajouts manuels",
        dot: COLORS.dot.fuchsia,
        badge: COLORS.badge.fuchsia,
        highlight: COLORS.highlight.fuchsia,
      },
      MISC: {
        label: "Autre",
        title: "Autres",
        dot: COLORS.dot.purple,
        badge: COLORS.badge.purple,
        highlight: COLORS.highlight.purple,
      },
      ORG: {
        label: "Organisation",
        title: "Organisations",
        dot: COLORS.dot.teal,
        badge: COLORS.badge.teal,
        highlight: COLORS.highlight.teal,
      },
      PER: {
        label: "Personne",
        title: "Personnes",
        dot: COLORS.dot.blue,
        badge: COLORS.badge.blue,
        highlight: COLORS.highlight.blue,
      },
      URL: {
        label: "URL",
        title: "Links",
        dot: COLORS.dot.red,
        badge: COLORS.badge.red,
        highlight: COLORS.highlight.red,
      },
    },
  },
};
